# Generated by Django 4.2.7 on 2023-11-05 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('franc_products_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
    ]
