# Generated by Django 4.2.7 on 2023-11-08 11:19

from django.db import migrations, models
import franc_setting.models


class Migration(migrations.Migration):

    dependencies = [
        ('franc_setting', '0002_sitesetting_about_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='Logo',
            field=models.ImageField(blank=True, null=True, upload_to=franc_setting.models.upload_image_path, verbose_name='تصویر'),
        ),
    ]
