# Generated by Django 4.2.7 on 2023-11-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franc_setting', '0004_alter_sitesetting_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='Copy_right',
            field=models.TextField(blank=True, null=True, verbose_name='متن کپی رایت'),
        ),
    ]
