# Generated by Django 4.2.7 on 2023-11-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franc_products_category', '0002_alter_productcategory_options'),
        ('franc_products', '0002_alter_product_options_alter_product_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, to='franc_products_category.productcategory', verbose_name='دسته بندی ها'),
        ),
    ]
