# Generated by Django 4.2.7 on 2023-11-07 07:37

from django.db import migrations, models
import django.db.models.deletion
import franc_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('franc_products', '0003_product_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان')),
                ('image', models.ImageField(blank=True, null=True, upload_to=franc_products.models.product_gallery_path, verbose_name='تصویر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franc_products.product')),
            ],
        ),
    ]
