# Generated by Django 4.2.7 on 2023-11-07 08:17

from django.db import migrations, models
import django.db.models.deletion
import franc_products.models


class Migration(migrations.Migration):

    dependencies = [
        ('franc_products', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'تصویر', 'verbose_name_plural': 'تصاویر'},
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(default=2, upload_to=franc_products.models.product_gallery_path, verbose_name='تصویر'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='franc_products.product', verbose_name='محصول'),
        ),
    ]
