# Generated by Django 4.2.7 on 2023-11-08 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('france_contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'تماس با ما', 'verbose_name_plural': 'تماس های کاربران'},
        ),
    ]
